iris-hep/func_adl

README.md
Add dynamic badges to the README that link to PyPI and display the current release of the library on PyPI 
[![PyPI version](https://badge.fury.io/py/func-adl.svg)](https://badge.fury.io/py/func-adl)
as well as the supported Python runtime versions for the library
[![Supported Python versions](https://img.shields.io/pypi/pyversions/func-adl.svg)](https://pypi.org/project/func-adl/)
=> Add PyPI release and supported Python badges

README.md
Add the following CI badge:
[![GitHub Actions Status](https://github.com/iris-hep/func_adl/workflows/CI/CD/badge.svg)](https://github.com/iris-hep/func_adl/actions)
=> Add GitHub Actions CI status badge to README

.gitignore
This helps keep the repo clean from the `git status` point of view.
=> Add coverage files to gitignore

func_adl/__init__.py, func_adl/event_dataset.py, func_adl/object_stream.py
- Remove some unused code
- Improve the comments
- Double check the code coverage (needed no changes)
Fixes #13
=> Code Clean up

.flake8, .vscode/settings.json, func_adl/ast/func_adl_ast_utils.py, func_adl/util_ast.py
This change properly:
- flake8 config file with line length monitoring
- makes sure integrated vscode flake8 runs correctly
fixes #48
=> Get flake8 running correctly

func_adl/event_dataset.py
Bug fix - make sure the query title is in the abstract interface
=> Fix missing title in abstract method

func_adl/event_dataset.py, func_adl/object_stream.py, tests/test_object_stream.py
* Passes typing info to calls
* Method completion doesn't work exactly right.
Fixes #79
=> Added typing into ObjectStream

.github/workflows/ci.yml, .vscode/settings.json, setup.py, setup_func_adl.py, setup_func_adl_ast.py
* Update CI to support python 10
* Update setup files to allow 3.10 installation
=> Support Python 10

.flake8, .vscode/settings.json, func_adl/__init__.py, func_adl/ast/aggregate_shortcuts.py, func_adl/ast/ast_hash.py, func_adl/ast/call_stack.py, func_adl/ast/func_adl_ast_utils.py, func_adl/ast/function_simplifier.py, func_adl/ast/meta_data.py, func_adl/event_dataset.py, func_adl/functions.py, func_adl/object_stream.py, func_adl/type_based_replacement.py, func_adl/util_ast.py, func_adl/util_types.py, pyproject.toml, setup.py, tests/ast/test_aggregate_shortcuts.py, tests/ast/test_ast_hash.py, tests/ast/test_func_adl_ast_utils.py, tests/ast/test_function_simplifier.py, tests/ast/test_meta_data.py, tests/ast/utils.py, tests/test_event_dataset.py, tests/test_object_stream.py, tests/test_type_based_replacement.py, tests/test_type_based_replacement_py310.py, tests/test_util_ast.py, tests/test_util_types.py, tests/util_debug_ast.py
Turning on black for everything (no precommit - just getting the formatting done). Also, isort.
=> Turning on black as a formatter

func_adl/util_ast.py, tests/test_util_ast.py
* Better testing for edge cases
* Deal with indents more naturally
* Allow supplying method name to parser for cases where things are too deep
=> More robust parsing of ast's from callables

func_adl/util_ast.py, tests/test_util_ast.py
* Multi-line parsing for lambdas
=> Regression (untested) for lambdas continuing accross lines

.vscode/settings.json, .vscode/tasks.json, func_adl/object_stream.py, func_adl/util_ast.py, tests/test_util_ast.py
* Added tests that show original bug
* A few other tests (like with other arguments) that might cause various solutions to get into trouble
* Remove depreciated settings from config for `vscode`.
* Major restructuring of how we parse out the source code - all tests are passing, but tread carefully, and if there are any problems please submit bug reports!
* Some minor length-of-line clean up
=> Support multi-line lambda functions which are valid before complete

func_adl/object_stream.py, tests/test_object_stream.py
=> Add `as_awkward` and `as_pandas`, etc

.github/workflows/ci.yml, setup.py
=> Python 3.11 support

func_adl/util_ast.py, tests/test_util_ast.py
* Found bug if a "word" wasn't at the end of the line, which was a bit of a dumb bug and a bit embarassing that none of my tests had covered it.
Fixes #110
=> Infinite loop if this lambda is parsed in Jupyter

.github/workflows/ci.yml, setup.py
* Update setup files to support 3.12
Fixes #128
=> Support Python 3.12

func_adl/ast/call_stack.py, tests/test_object_stream.py
* Type check to make sure netsted classes of enums are done right
* The issue being addressed turned out to be elsewhere, so we got a new test and some clean up here.
* Fix up new flake8/black errors
=> Enable Enums

.github/workflows/ci.yml, func_adl/type_based_replacement.py, func_adl/util_types.py, tests/test_type_based_replacement.py
* Implement type following thru dictionary accesses
* Implement type following thru tuple index references
* Fix up flake8 and pylance type follow errors.
* Fix up github action references
Fixes #139
=> Type propagation through dict and tuples

CITATION.cff
Add a citation in the proper format.
Fixes #155
=> Add preferred citation and CITAITON.cff

README.md
* c.f. https://github.com/conda-forge/func-adl-feedstock
[![conda-forge version](https://img.shields.io/conda/vn/conda-forge/func-adl.svg)](https://github.com/conda-forge/func-adl-feedstock.git)
=> docs: Add conda-forge badge to README

pyproject.toml
Fix up project distribution 
Fixes #167
=> Fixup project distriubtion files

func_adl/type_based_replacement.py, tests/test_type_based_replacement.py
* Support `info["pt"]` access rather than just `info.pt`.
Fixes #169
=> Support Slice Reference to Dictionary Access

.vscode/settings.json, README.md
Very small addition... just to finish up what should have been in the prevous PR!
=> Add docs for named tuples and data classes
