iris-hep/func_adl

- .coveragerc
- .github/workflows/ci.yml
- .travis.yml
- pytest.ini
* Test Python 3.6 and Python 3.7 across Ubuntu, MacOS, and Windows using GitHub Actions CI
* Add `pytest-cov` dependency
* Add pytest.ini and .coveragerc to simplify signatures
Additionally remove codecov reporting on Travis so that you don't run into an issue with two coverage reports being uploaded.
> Add CI using GitHub Actions

- .github/workflows/ci.yml
To fix the reporting of coverage (I'm not sure what happened that it broke, as it is a bit hard to trace things at the moment &mdash; probably from an old PR of mine not getting rebased before merge) use the [GitHub Actions Codecov](https://github.com/marketplace/actions/codecov) app to upload and report the coverage.
c.f. https://github.com/codecov/codecov-action
This seems to be the more supported solution then using https://github.com/codecov/codecov-python.
> Use Codecov GitHub actions app to report coverage

- func_adl/util_ast.py
With the [release of `flake8` `v3.8.0` today](https://gitlab.com/pycqa/flake8/-/blob/master/docs/source/release-notes/3.8.0.rst) it seems that some rules are now [breaking CI](https://github.com/iris-hep/func_adl/runs/665277094?check_suite_focus=true). To placate [`flake8` E741](https://www.flake8rules.com/rules/E741.html) the use of the single letter variable `l` (for lambda) has been replaced with `lam`. This is chosen over adding [E741](https://www.flake8rules.com/rules/E741.html) to the ignore list, as the rule does help check readability.
> fix: Use 'lam' over 'l' to placate flake8 E741

- func_adl/__init__.py
- func_adl/event_dataset.py
- func_adl/object_stream.py
- tests/test_event_dataset.py
- tests/test_object_stream.py
Move to a system where the object we have is not the same name as the file.
Fixes #33
> Updat naming (#33)

- func_adl/event_dataset.py
- tests/test_event_dataset.py
Make sure that an EventDataset can deal with various arguments. In particular, a tree name aimed at uproot!
Fixes #40
> EventDataset can have as many arguments as it wants

- func_adl/object_stream.py
ObjectSteam creates references to itself. Type information should be specified. Unfortunately, type annotations do not exist in the futures for 3.6 - as a result we need to fake it out.
Working on #43
> Switch how we list the return type

- func_adl/event_dataset.py
- func_adl/object_stream.py
- tests/test_event_dataset.py
- tests/test_object_stream.py
- Also will break anyone's direct internal access to the `_ast` variable, forcing them to update to use the public API
Fixes #39
> add a query_ast property to ObjectStream for access.

- .vscode/settings.json
- func_adl/object_stream.py
- func_adl/util_ast.py
- tests/test_object_stream.py
- tests/test_util_ast.py
Add code to accept raw source code `lambda` in `Select` and `Where` statements.
- This relies on python's `inspect.source` library. At least in 3.7 and 3.6
- This is quite brittle. There are tests that look for problems in the way things are called.
- Exceptions with some text and source code are thrown when the `lambda` can't be determined.
The problem is that this can't do a more complex lambda function that inline the way we often see them in `func_adl`:
```python
def test_run_on_parse():
'Emulate the syntax you often find when you have a multistep query'
class my_obj:
def do_it(self, x: Callable):
parse_as_ast(x)
return self
with pytest.raises(Exception):
long_expr = my_obj() \
.do_it(lambda x: x + 1) \
.do_it(lambda y: y + 2)
```
For this `inspect.getsource` returns:
``` …
```
> Parse Lambda's inline

- .flake8
- .github/workflows/ci.yml
- .gitignore
- .vscode/settings.json
- func_adl/ast/aggregate_shortcuts.py
- func_adl/ast/call_stack.py
- func_adl/ast/function_simplifier.py
- func_adl/event_dataset.py
- func_adl/object_stream.py
- func_adl/util_ast.py
- setup.py
- tests/ast/test_aggregate_shortcuts.py
- tests/test_util_ast.py
The `ast` module and how python parses code changes in some small ways moving between python versions 3.7 and 3.9. This set of changes updates this package to run in anything from 3.6 to 3.9.
All changes should be backwards compabile.
It should be noted that just because this works doesn't mean it can be used: a client running in 3.8 sending to a service running in 3.7 has not yet been tested.
> Make compatible with 3.8 and 3.9

- func_adl/event_dataset.py
- func_adl/object_stream.py
- tests/test_event_dataset.py
Changes the underlying way information is passed around in `EventDataSet` when it is converted to a python `AST`. Instead of storing a pointer back to an object, it stores the arguments used to create it in the first place. This specifically enables scenarios like #64 for `uproot`, and will also fix up issues likely to be encountered when doing the same thing for `xAOD`. Consider this cleaning up technical debt.
Should have no outward-facing changes.
Resolves #64.
> Store executor in hidden attribute of AST and remove EventDataset object from args

- func_adl/ast/function_simplifier.py
- tests/ast/test_function_simplifier.py
* `{'e1': t1, 'e2': t2}.e1` or `{'e1': t1, 'e2': t2}.['t1']` both evaluate to `t1`.
* A method call on the result of a `First` gets moved inside the `First` with a `Select` - this is partly because a method call very much looks like the lookup for the dictionary.
Supporting tests fixed.
This should cause no functional changes downstream, but it might mess up some of the tests in `func_adl_xAOD`.
Fixes #61
> Support Dictionaries internally in the query

- .vscode/tasks.json
- func_adl/event_dataset.py
- tests/test_event_dataset.py
* Add a reference to the event data set
* Add tests to cover finding the event data set ast node
* Add task to run code coverage easily
This will make it possible for an external library to recover the origianl EventDataset object from deep in a query hierarchy
> Recover EventDataset object from complex query

- func_adl/ast/__init__.py
- func_adl/ast/meta_data.py
- func_adl/object_stream.py
- tests/ast/test_function_simplifier.py
- tests/ast/test_meta_data.py
- tests/ast/utils.py
- tests/test_object_stream.py
This will allow streaming of dictionary based `MetaData` when being sent over the wire. The metadata is designed for:
* Declaring new C++ native code functions
* Declaring new collections on a C++ backend
* Declaring method return types
The dictionary values and types and their meaning is set by the backend one is corresponding to.
Types that can be sent are the collection of all valid `qastle` types.
This PR contains:
- Extension to the `ObjectStream` object with a `MetaData` method
- A function that will return a new AST with all `MetaData` removed, along with an ordered list of the `MetaData`.
> Add a function to allow MetaData over the wire

- func_adl/ast/meta_data.py
- func_adl/object_stream.py
- tests/ast/test_meta_data.py
- tests/test_object_stream.py
Add the `QMetaData` extension.
* API is same as for `MetaData`
* No data is sent down to the xAOD backend
* Lookup can be performed on the query to find values
* Warnings issued if there is an attempt to override various things already set.
> Pr_query_metadata

- func_adl/util_ast.py
- tests/test_util_ast.py
* Fixes a bug that is part of captured variables logic
* If `jets` was used as both a lambda argument an a global constant, then it would be replaced by its value in the AST
Fixes #95
> Bug Fix: argument names should override captured variables

- tests/test_util_ast.py
The new parser turns out to be quite happy with this format. Adding a test to make sure we have no regression
Fixes #84
> Test to make sure multi-line lambda with funny breaks works

- func_adl/util_ast.py
- tests/test_util_ast.py
Minor update to parse another case often created by black
* Split lambda from first line, but invoke again with the calling function
* Improve two checks for lack of lambda's - and add error message to failed assert.
Fixes #108
> Pr_nested_function_names

- func_adl/object_stream.py
- func_adl/util_ast.py
- tests/test_object_stream.py
- tests/test_util_ast.py
* Make sure we use the fact we are after a `Where` or `Select` when parsing multiple `lambda`'s on a line
* Improve the error message when we can't tell the difference between mtuple lambda's.
Fixes #115
> Use Function Names as Clues Parsing Lambda's

- .gitignore
- func_adl/object_stream.py
- setup.py
Each of the ObjectStream operations (Select, Where, etc) create a new ObjectStream instance. If a developer has subclassed ObjectStream and stored values in the instance variables, this information is lost at each step in the chain of operations.
We need a way to preserve the original subclass and instance as we construct the AST.
Instead of returning a new instance of ObjectStream use a `deepcopy` of input object at each step.
> Allow object stream operations to retain original subclass

- .github/workflows/ci.yml
- func_adl/object_stream.py
- tests/test_object_stream.py
* Empty MetaData calls are illegal - and cause a backend crash
* The QMetaData, if called first, can generate an empty metadata call
* Prevent this by properly creating a new empty `ast`
> Do not add an empty MetaData call

- func_adl/util_ast.py
- setup.py
- tests/test_object_stream.py
- tests/test_util_ast.py
Passing through `np` and other module names for some functions didn't work if `np` had already been imported into the namespace. This fixes that and improves error messages around non-standard lambda captures.
* `ModuleType` is now "captured" as just the name you use. So `np` and `numpy` are both passed down (warning!). `np` should no work both if or if it hasn't been imported.
* White list for types of things that can be sent down: `str, int, float, bool, complex, str,` and `bytes`.
* Added `numpy` to test install flavor so this functionality could be tested. 
Fixes #127
> Imported module names/function should be correctly passed to qastle.

- .flake8
- func_adl/ast/function_simplifier.py
- func_adl/type_based_replacement.py
- func_adl/util_ast.py
- setup.py
Resolves #101
* For the requires-python metadata, require Python 3.7+ as all CPython versions up through Python 3.7 are now EOL. Python 3.7 support should also be dropped, but that can be done incrementally.
```
┌───────┬────────────┬─────────┬────────────────┬────────────┬────────────┐
│ cycle │  release   │ latest  │ latest release │  support   │    eol     │
├───────┼────────────┼─────────┼────────────────┼────────────┼────────────┤
│ 3.12  │ 2023-10-02 │ 3.12.2  │   2024-02-06   │ 2025-04-02 │ 2028-10-31 │
│ 3.11  │ 2022-10-24 │ 3.11.8  │   2024-02-06   │ 2024-04-01 │ 2027-10-31 │
│ 3.10  │ 2021-10-04 │ 3.10.13 │   2023-08-24   │ 2023-04-05 │ 2026-10-31 │
│ 3.9   │ 2020-10-05 │ 3.9.18  │   2023-08-24   │ 2022-05-17 │ 2025-10-31 │
│ 3.8   │ 2019-10-14 │ 3.8.18  │   2023-08-24   │ …
```
> build: Support Python 3.7+

- func_adl/type_based_replacement.py
- tests/test_type_based_replacement.py
* Created dictionaries are assigned to a data-class
* Data class is correctly typed
* Data class is de-referenced as needed.
This is only done during type resolution. The hope is this will not affect any other part of the work flow.
Help working towards [idap 200](https://github.com/iris-hep/idap-200gbps-atlas/issues/47) test.
> Deep-Type Dictionaries

- func_adl/ast/function_simplifier.py
- func_adl/type_based_replacement.py
- tests/test_type_based_replacement.py
* When `Zip` or `zip` is used on a dictionary, the type follower punts and returns only `Any`
* This will prevent the crash seen in this bug report.
* The correct types can be followed through here. See #150 for more information.
Closes #148
> Type-Checking the Zip operator on Dictionary should not crash

- func_adl/type_based_replacement.py
- tests/test_type_based_replacement.py
* Added `len` as an "internal" function, much the way `abs` is already added.
* Added small test to make sure this fixes the warning we've been seeing.
Fixes #146
> Test that triggers the `len` error

- CITATION.cff
- README.md
* Add citation information for the code and keep the paper as a reference.
- Add metadata for CFF version as well as author metadata.
* Add preferred citation information to README.
* Amends PR https://github.com/iris-hep/func_adl/pull/157
> fix: Add citation information for repository

- .github/workflows/ci.yml
- .github/workflows/pypi.yaml
- func_adl/type_based_replacement.py
- func_adl/util_types.py
- setup.py
* Resolves #158 
* Resolves #163
* Require Python 3.9+, dropping support for Python 3.7 and 3.8 as both are EOL, and Python 3.8+ syntax is already being used in the current release which already EOLs 3.7.
* Update minimum Python used in CI to 3.9.
There are stil Python 3.7 specific notes in the code:
```console
$ git grep "3\.7"
func_adl/ast/function_simplifier.py:442:        # Get the value out - this is due to supporting python 3.7-3.9
func_adl/ast/function_simplifier.py:567:    """Deal with 3.7, and 3.8 differences in how indexing for list and tuple
func_adl/type_based_replacement.py:946:            "3.7 compatibility"
func_adl/type_based_replacement.py:951:            "3.7 compatibility"
func_adl/type_based_replacement.py:956:            "3.7 compatibility"
func_adl/util_types.py:25: …
```
> build: Support Python 3.9+ 

- func_adl/ast/func_adl_ast_utils.py
- func_adl/ast/function_simplifier.py
- func_adl/object_stream.py
- func_adl/type_based_replacement.py
- func_adl/util_ast.py
- tests/ast/test_func_adl_ast_utils.py
- tests/test_event_dataset.py
Since we no longer supporting Python 3.7, a lot of legacy code can be removed. This will be required anyway as we move to python 3.14 where a lot of this stuff simply disappears.
* Remove all `ast.Num` support
* Remove all `ast.Str` support
* Remove all `ast.NameConstant` support
* Update use of `ast.expr` to remove lots of `cast` operations.
Fixes #171
> Remove legacy ast support (pre 3.9)

- .github/workflows/ci.yml
- README.md
- func_adl/util_ast.py
- tests/test_util_ast.py
- tests/xAOD/__init__.py
* Add support for enum's by evaluating them inline (e.g. like a captured constant or variable)
* Support similar for class constants.
* Improve the running of CI so only on PR's or direct pushes to master.
> Support enums and class constants

- func_adl/ast/syntatic_sugar.py
- func_adl/util_ast.py
- tests/ast/test_syntatic_sugar.py
- tests/test_type_based_replacement.py
- tests/test_util_ast.py
* Dataclasses are replaced by dictionaries as syntatic sugar
* named tuples are also replaced by dictionaries as syntatic sugar
These changes should enable the user to build a EDM with a dataclass or named tuple, and have type checking follow it!
Fixes #63
> Add dataclasses and named tuples as syntatic sugar
